### ISSUE TITLE
Please update the repository, if you have latest code. Thanks!

### ISSUE THREAD

**Issue by prabhu1984** [wdavidw/webhdfs-java-client#1]
Please update the repository, if you have latest code. Thanks!

**Comment by wdavidw** [comment]
It's a project that I started and finally dropped. I ended up with a nodejs approach using usual HTTP [request](https://github.com/request/request) calls where the HTTP header is enriched with [spnego](https://github.com/adaltas/node-krb5).

**Comment by prabhu1984** [comment]
Thanks for the updates! Have a good week!
